name: Build Windows (PySide6-Deploy + PyInstaller)
on: [push, workflow_dispatch]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup venv and install deps
        shell: cmd
        run: |
          python -m venv .venv
          call .venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install pyside6==6.7.2

      - name: Verify pysidedeploy.spec exists at repo root
        shell: pwsh
        run: |
          if (-not (Test-Path pysidedeploy.spec)) {
            Write-Error "pysidedeploy.spec not found at repo root. Commit it or adjust the path."
            exit 1
          }
          Write-Host '--- pysidedeploy.spec ---'
          Get-Content pysidedeploy.spec

      - name: Build (pyside6-deploy with PyInstaller backend)
        shell: cmd
        run: |
          call .venv\Scripts\activate
          pyside6-deploy -c pysidedeploy.spec --extra-ignore-dirs .venv --force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioSocketClient-win
          if-no-files-found: error
          path: |
            build/win/**
            pyside6_deploy/**