name: Build Linux
on:
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install runtime libs
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libx11-xcb1 \
            libxcb1 \
            libxkbcommon-x11-0 \
            libxrender1 \
            libxcomposite1 \
            libxcursor1 \
            libxi6 \
            libxtst6 \
            libxrandr2 \
            libnss3 \
            libglib2.0-0 \
            libdbus-1-3 \
            libasound2 \
            libxshmfence1 \
            libgl1 \
            python3 \
            python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          pip install "PySide6<6.6" "shiboken6<6.6" pyinstaller sounddevice websocket-client

      - name: Build with PyInstaller
        run: |
          pyinstaller --name AudioSocketClient --windowed --noconfirm \
            --collect-all PySide6 \
            --collect-all shiboken6 \
            --hidden-import=socket \
            --hidden-import=websocket \
            --hidden-import=sounddevice \
            main.py

      - uses: actions/upload-artifact@v4
        with:
          name: AudioSocketClient-linux
          path: dist/AudioSocketClient/**