name: Build Windows (pyside6-deploy)
on: [push, workflow_dispatch]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # 或 3.11，記得是 x64（預設即 x64）

      - name: Install deps
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install pyside6 pyside6-deploy

      # 第一次可以先產生設定檔；之後專案固定就保留版本控管
      - name: Init deploy config (first time only)
        if: ${{ !exists('pyside6-deploy.json') }}
        shell: cmd
        run: pyside6-deploy --init main.py

      # 直接依照設定檔打包
      - name: Build with pyside6-deploy
        shell: cmd
        run: pyside6-deploy pyside6-deploy.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioSocketClient-win
          path: |
            pyside6_deploy/**/dist/**