name: Build Windows (PySide6-Deploy)
on: [workflow_dispatch, push]

jobs:
  build-win:
    runs-on: windows-latest
    env:
      PYSIDE_DISABLE_PROMPTS: "1"      # 關閉互動詢問
      QT_DEBUG_PLUGINS: "0"
      # 讓 Nuitka 自動下載 dependency-walker，不要卡互動
      NUITKA_USE_CACHE: "yes"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup venv & deps (venv 放 RUNNER_TEMP 避免被掃 QML)
        shell: pwsh
        run: |
          $venv = Join-Path $env:RUNNER_TEMP "asc-venv"
          python -m venv $venv
          . "$venv\Scripts\Activate.ps1"
          pip install --upgrade pip
          pip install "pyside6==6.7.2"
          echo "VENV=$venv" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Export NUITKA_CACHE_DIR from RUNNER_TEMP
        shell: pwsh
        run: |
          $cache = Join-Path $env:RUNNER_TEMP 'nuitka-cache'
          echo "NUITKA_CACHE_DIR=$cache" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Ensure pysidedeploy.spec at repo root
        shell: pwsh
        run: |
          if (-not (Test-Path ".\pysidedeploy.spec")) {
            Write-Error "pysidedeploy.spec not found at repo root"; exit 1
          }
          Write-Host "--- pysidedeploy.spec ---"
          Get-Content .\pysidedeploy.spec

      - name: Build (pyside6-deploy)
        shell: pwsh
        run: |
          . "$env:VENV\Scripts\Activate.ps1"
          pyside6-deploy -c pysidedeploy.spec --force --dry-run

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioSocketClient-win
          if-no-files-found: error
          path: |
            deployment/**
            pyside6_deploy/**